'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import {
  CalendarDays, Cake, Check, ClipboardList, Clock3, FilePlus2, FileText,
  History, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Search,
  Settings, Stethoscope, UserRound, UserPlus, Users, X,
} from 'lucide-react';
import type { Appointment, City, Consultation, Contact, Patient, Prescription, Profile, Schedule, Store } from '@/types/essencialy';
import { br, cash, digits, iso, printDeclaration, tomorrow } from '@/lib/essencialy-utils';
import { Empty, Modal, Status } from '@/components/essencialy/shared-ui';
export function DirectPage({setModal}:any){return <section><h2 className="text-3xl font-black">Cadastro direto</h2><p className="text-[#778079]">Registre paciente e receita anterior sem criar uma consulta.</p><button className="btn-primary mt-5" onClick={()=>setModal('direct')}><Plus className="inline" size={18}/> Novo cadastro direto</button></section>}
export function DirectForm({profile,patients,close,load,flash}:any){
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const cpf=digits(String(f.get('cpf')));let patientId=cpf?(patients.find((p:Patient)=>digits(p.cpf||'')===cpf)?.id||''):'';if(!patientId){const {data,error}=await supabase.from('patients').insert({full_name:f.get('name'),cpf:cpf||null,phone:digits(String(f.get('phone'))),birth_date:f.get('birth_date')||null,address:f.get('address')||null,created_by:profile.id,created_store_id:profile.store_id,triage:{complaint:f.get('complaint'),ocular_history:f.get('ocular_history'),ocular_surgery:f.get('ocular_surgery'),conditions:f.get('conditions')}}).select().single();if(error)return flash(error.message);patientId=data.id}
 const data={od_spherical:f.get('od_spherical'),od_cylindrical:f.get('od_cylindrical'),od_axis:f.get('od_axis'),oe_spherical:f.get('oe_spherical'),oe_cylindrical:f.get('oe_cylindrical'),oe_axis:f.get('oe_axis'),addition:f.get('addition')};
 const {error}=await supabase.from('prescriptions').insert({patient_id:patientId,professional_id:profile.role==='RECEPCAO'?null:profile.id,exam_date:f.get('exam_date'),data,pupillary_distance:f.get('dp')||null,notes:f.get('notes')||null,source:'DIRECT_ENTRY'});if(error)return flash(error.message);flash('Cadastro direto e receita anterior salvos.');close();load();}
 return <Modal title="Cadastro direto" close={close}><form onSubmit={save} className="grid sm:grid-cols-2 gap-3">
  <h3 className="font-black sm:col-span-2">Dados do paciente</h3><label className="label">Nome<input className="field" name="name" required/></label><label className="label">CPF<input className="field" name="cpf"/></label><label className="label">Nascimento<input className="field" type="date" name="birth_date"/></label><label className="label">Telefone<input className="field" name="phone" required/></label><label className="label sm:col-span-2">Endereço<input className="field" name="address"/></label>
  <h3 className="font-black sm:col-span-2">Anamnese</h3>{['complaint','ocular_history','ocular_surgery','conditions'].map((n,i)=><label className="label" key={n}>{['Motivo/queixa','Histórico ocular','Cirurgias','Condições relevantes'][i]}<textarea className="field" name={n}/></label>)}
  <h3 className="font-black sm:col-span-2">Receita</h3><section className="sm:col-span-2 overflow-x-auto rounded-xl border bg-white p-3"><table className="w-full min-w-[520px] text-center text-sm"><thead><tr><th className="p-2">Olho</th><th className="p-2">Esf</th><th className="p-2">Cil</th><th className="p-2">Eixo</th></tr></thead><tbody>{(['od','oe'] as const).map(eye=><tr key={eye}><th className="p-2 text-[#9a7b2f]">{eye.toUpperCase()}</th><td className="p-1"><input className="field text-center" name={`${eye}_spherical`} placeholder="+ / -"/></td><td className="p-1"><input className="field text-center" name={`${eye}_cylindrical`} placeholder="+ / -"/></td><td className="p-1"><input className="field text-center" name={`${eye}_axis`}/></td></tr>)}</tbody></table><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="label">Adição<input className="field" name="addition"/></label><label className="label">DP<input className="field" name="dp"/></label></div></section><label className="label">Data do exame<input className="field" name="exam_date" type="date" required/></label><label className="label">Observações<textarea className="field" name="notes"/></label><button className="btn-primary sm:col-span-2">Salvar histórico</button>
 </form></Modal>
}
