'use client';

import { FormEvent, useMemo, useState } from 'react';
import { ClipboardPlus, Edit3, Printer, Trash2, UserRound } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Consultation, Patient, Prescription, TriageRecord } from '@/types/essencialy';
import { br, digits, printPrescription } from '@/lib/essencialy-utils';
import { Empty, Modal, TriageSummary } from '@/components/essencialy/shared-ui';

export function Patients({ patients, setTarget, setModal, setView }: any) {
  const [q, setQ] = useState('');
  const normalized = q.trim().toLowerCase();
  const list = useMemo(() => [...patients].filter((p: Patient) => {
    const text = `${p.full_name} ${p.phone || ''} ${p.cpf || ''}`.toLowerCase();
    const numbers = digits(q);
    return text.includes(normalized) || Boolean(numbers && `${digits(p.phone)} ${digits(p.cpf || '')}`.includes(numbers));
  }).sort((a: Patient, b: Patient) => a.full_name.localeCompare(b.full_name, 'pt-BR')), [patients, normalized, q]);
  return <>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-[#8a7560]">Cadastro único</p><h2 className="text-3xl font-black">Pacientes</h2></div><label className="label w-full sm:max-w-md">Pesquisar por nome, CPF ou telefone<input className="field" placeholder="Digite para pesquisar" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
    <div className="mt-5 overflow-hidden rounded-xl border bg-white">{list.map((p: Patient) => <article key={p.id} className="grid gap-4 border-b p-4 last:border-b-0 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid size-11 place-items-center rounded-full bg-[#edf2ef] font-black">{p.full_name[0]}</span><div><h3 className="font-black">{p.full_name}</h3><p className="text-sm text-[#778079]">CPF: {p.cpf || '—'} · {p.phone || '—'}</p></div><div className="flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>{setTarget(p);setModal('patient')}}><UserRound className="mr-1 inline" size={16}/> Abrir</button><button className="btn-secondary" onClick={()=>{setTarget(p);setModal('');setView('triagem')}}><ClipboardPlus className="mr-1 inline" size={16}/> Nova triagem</button></div></article>)}{!list.length && <Empty>Nenhum paciente encontrado.</Empty>}</div>
  </>;
}

export function PatientRecord({patient,profile,consultations,prescriptions,triageRecords=[],close,load,flash,setTarget,setModal,setView}:any){
  const [editing,setEditing]=useState(false);
  const histories=useMemo(()=>{
    const items=new Map<string,{date:string;consultations:Consultation[];prescriptions:Prescription[];triages:TriageRecord[]}>();
    const take=(date:string)=>{const key=date.slice(0,10);if(!items.has(key))items.set(key,{date:key,consultations:[],prescriptions:[],triages:[]});return items.get(key)!};
    consultations.filter((c:Consultation)=>c.patient_id===patient.id).forEach((c:Consultation)=>take(c.exam_date).consultations.push(c));
    prescriptions.filter((r:Prescription)=>r.patient_id===patient.id).forEach((r:Prescription)=>take(r.exam_date).prescriptions.push(r));
    triageRecords.filter((t:TriageRecord)=>t.patient_id===patient.id).forEach((t:TriageRecord)=>take(t.recorded_at).triages.push(t));
    return [...items.values()].sort((a,b)=>b.date.localeCompare(a.date));
  },[patient.id,consultations,prescriptions,triageRecords]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('patients').update({full_name:f.get('name'),phone:digits(String(f.get('phone'))),cpf:digits(String(f.get('cpf')))||null,rg:f.get('rg')||null,birth_date:f.get('birth_date')||null,address:f.get('address')||null,city_name:f.get('city_name')||null,notes:f.get('notes')||null,updated_at:new Date().toISOString()}).eq('id',patient.id);if(error)return flash(error.message);flash('Dados pessoais atualizados.');setEditing(false);await load();}
  async function remove(){if(!window.confirm(`Excluir definitivamente ${patient.full_name} e todo o histórico?`))return;const {error}=await supabase.from('patients').delete().eq('id',patient.id);if(error)return flash(error.message);flash('Paciente excluído.');close();load();}
  return <Modal title={`Ficha do paciente · ${patient.full_name}`} close={close} wide>
    <section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-[#8a918c]">Dados pessoais</p><h3 className="mt-1 text-xl font-black">{patient.full_name}</h3></div>{!editing&&<button className="btn-secondary" onClick={()=>setEditing(true)}><Edit3 className="mr-1 inline" size={16}/> Editar cadastro</button>}</div>
      {editing?<form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="label">Nome<input className="field" name="name" defaultValue={patient.full_name} required/></label><label className="label">Telefone<input className="field" name="phone" defaultValue={patient.phone} required/></label><label className="label">CPF<input className="field" name="cpf" defaultValue={patient.cpf}/></label><label className="label">RG<input className="field" name="rg" defaultValue={patient.rg}/></label><label className="label">Nascimento<input className="field" type="date" name="birth_date" defaultValue={patient.birth_date}/></label><label className="label">Cidade/Estado<input className="field" name="city_name" defaultValue={patient.city_name}/></label><label className="label sm:col-span-2">Endereço<input className="field" name="address" defaultValue={patient.address}/></label><label className="label sm:col-span-2">Observações<textarea className="field" name="notes" defaultValue={patient.notes}/></label><div className="flex gap-2 sm:col-span-2"><button className="btn-primary">Salvar dados</button><button type="button" className="btn-secondary" onClick={()=>setEditing(false)}>Cancelar</button></div></form>:<div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><p><b>CPF:</b> {patient.cpf||'—'}</p><p><b>RG:</b> {patient.rg||'—'}</p><p><b>Telefone:</b> {patient.phone||'—'}</p><p><b>Nascimento:</b> {br(patient.birth_date)}</p><p><b>Cidade:</b> {patient.city_name||'—'}</p><p className="sm:col-span-2"><b>Endereço:</b> {patient.address||'—'}</p>{patient.notes&&<p className="sm:col-span-2"><b>Observações:</b> {patient.notes}</p>}</div>}
    </section>
    <section className="mt-6"><div className="flex items-center justify-between"><h3 className="text-xl font-black">Histórico clínico</h3><button className="btn-secondary" onClick={()=>{setTarget(patient);setModal('');setView('triagem')}}><ClipboardPlus className="mr-1 inline" size={16}/> Nova triagem</button></div><div className="mt-3 space-y-4">{histories.map(group=><article className="card overflow-hidden" key={group.date}><header className="bg-[#111] px-5 py-3 text-white"><b>{br(group.date)}</b></header><div className="space-y-5 p-5">{(group.triages.length?group.triages.map(t=><div key={t.id}><h4 className="font-black">Anamnese</h4><TriageSummary triage={t.data}/></div>):group.consultations.length?<div><h4 className="font-black">Anamnese</h4><TriageSummary triage={patient.triage}/></div>:null)}{group.consultations.map(c=><div key={c.id}><h4 className="font-black">Consulta</h4><p className="mt-1 text-sm"><b>Retorno:</b> {br(c.return_date)}</p>{c.clinical_notes&&<p className="mt-1 whitespace-pre-wrap text-sm">{c.clinical_notes}</p>}</div>)}{group.prescriptions.map(rx=><div key={rx.id}><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-black">Receita</h4><button className="btn-secondary" onClick={()=>printPrescription(patient,rx)}><Printer className="mr-1 inline" size={16}/> Imprimir somente receita</button></div><PrescriptionView rx={rx}/></div>)}</div></article>)}{!histories.length&&<div className="card"><Empty>Nenhum histórico clínico registrado.</Empty></div>}</div></section>
    <footer className="sticky -bottom-5 -mx-5 mt-7 flex flex-wrap justify-between gap-3 border-t bg-[#f8f6f1] p-5"><button className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 font-bold text-red-700 disabled:opacity-50" disabled={profile?.role!=='ADMIN'} title={profile?.role!=='ADMIN'?'Somente administradores podem excluir pacientes':''} onClick={remove}><Trash2 className="mr-1 inline" size={16}/> Excluir paciente</button><button className="btn-secondary" onClick={close}>Fechar ficha</button></footer>
  </Modal>;
}

export function PrescriptionView({rx}:{rx:Prescription}){const d:any=rx.data||{};return <div className="mt-2 overflow-x-auto"><table className="w-full min-w-[460px] border-collapse text-center text-sm"><thead><tr className="bg-[#f1ead7]"><th className="border p-2">Olho</th><th className="border p-2">Esférico</th><th className="border p-2">Cilíndrico</th><th className="border p-2">Eixo</th></tr></thead><tbody><tr><th className="border p-2">OD</th><td className="border p-2">{String(d.od_spherical??d.esfAtualOd??'—')}</td><td className="border p-2">{String(d.od_cylindrical??d.cilAtualOd??'—')}</td><td className="border p-2">{String(d.od_axis??d.eixAtualOd??'—')}</td></tr><tr><th className="border p-2">OE</th><td className="border p-2">{String(d.oe_spherical??d.esfAtualOe??'—')}</td><td className="border p-2">{String(d.oe_cylindrical??d.cilAtualOe??'—')}</td><td className="border p-2">{String(d.oe_axis??d.eixAtualOe??'—')}</td></tr></tbody></table><p className="mt-2 text-sm"><b>Adição:</b> {String(d.addition??d.addAtual??'—')} · <b>DP:</b> {rx.pupillary_distance||'—'}</p></div>}
