'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import {
  CalendarDays, Cake, Check, ClipboardList, Clock3, FilePlus2, FileText,
  History, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Search,
  Settings, Stethoscope, UserRound, UserPlus, Users, X,
} from 'lucide-react';
import type { Appointment, City, Consultation, Contact, Patient, Prescription, Profile, Schedule, Store } from '@/types/essencialy';
import { br, cash, digits, iso, printDeclaration, tomorrow } from '@/lib/essencialy-utils';
import { Empty, Modal, Status } from '@/components/essencialy/shared-ui';
export function UsersPage({profiles,cities,stores,setModal,setTarget}:any){return <><div className="flex justify-between"><div><h2 className="text-3xl font-black">Usuários</h2><p className="text-[#778079]">Acessos, perfis e unidades.</p></div><button className="btn-primary" onClick={()=>setModal('user')}><UserPlus className="inline" size={18}/> Novo usuário</button></div><div className="grid md:grid-cols-2 gap-4 mt-5">{profiles.map((p:Profile)=><article className="card p-5" key={p.id}><b>{p.full_name||p.email}</b><p className="text-sm">{p.email}</p><Status value={p.role}/><p className="text-xs mt-2">{cities.find((c:City)=>c.id===p.city_id)?.name||'Sem cidade'} · {stores.find((s:Store)=>s.id===p.store_id)?.name||'Sem ótica'}</p><button className="btn-secondary mt-4" onClick={()=>{setTarget(p);setModal('password')}}>Alterar senha</button></article>)}</div></>}
export function UserForm({cities,stores,close,load,flash}:any){const[city,setCity]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await supabase.functions.invoke('create-user',{body});if(error||!data?.ok)return flash(data?.error||error?.message||'Não foi possível criar o usuário.');flash('Usuário criado com sucesso.');close();load()}return <Modal title="Novo usuário" close={close}><form onSubmit={save} className="grid sm:grid-cols-2 gap-4"><label className="label">Nome<input className="field" name="name" required/></label><label className="label">E-mail<input className="field" type="email" name="email" required/></label><label className="label">Senha<input className="field" type="password" minLength={8} name="password" required/></label><label className="label">Perfil<select className="field" name="role" required><option value="AGENDA">Somente agenda</option><option value="RECEPCAO">Recepção</option><option value="OPTOMETRISTA">Optometrista</option><option value="ADMIN">Administrador</option></select></label><label className="label">Cidade<select className="field" name="city_id" value={city} onChange={e=>setCity(e.target.value)} required><option value="">Selecione</option>{cities.map((c:City)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="label">Ótica<select className="field" name="store_id" required><option value="">Selecione</option>{stores.filter((s:Store)=>s.city_id===city).map((s:Store)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="btn-primary sm:col-span-2">Criar usuário</button></form></Modal>}

export function PasswordForm({target,close,flash}:any){const[busy,setBusy]=useState(false);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get('password')||'');const confirmation=String(f.get('confirmation')||'');if(password!==confirmation)return flash('As senhas não coincidem.');setBusy(true);const{data,error}=await supabase.functions.invoke('update-user-password',{body:{user_id:target.id,password}});setBusy(false);if(error||!data?.ok)return flash(data?.error||error?.message||'Não foi possível alterar a senha.');flash('Senha alterada com sucesso.');close()}return <Modal title={`Alterar senha · ${target.full_name||target.email}`} close={close}><form onSubmit={save} className="space-y-4"><p className="text-sm text-[#778079]">Defina uma nova senha com pelo menos 8 caracteres.</p><label className="label">Nova senha<input className="field" name="password" type="password" minLength={8} autoComplete="new-password" required/></label><label className="label">Confirmar nova senha<input className="field" name="confirmation" type="password" minLength={8} autoComplete="new-password" required/></label><button className="btn-primary w-full" disabled={busy}>{busy?'Alterando...':'Alterar senha'}</button></form></Modal>}
